### ISSUE TITLE
Wrong Functions

### ISSUE THREAD

**Issue by i-Naji** [Josepdal/DBTeamV3#1]
Necessary general changes in some functions:
getChats :
[`limit_ > limit`](https://github.com/Josepdal/DBTeamV3/blob/5ff040368c26f776aa64cc130b980863bf67db22/bot/methods.lua#L130)

changeAbout :
[`about_ > about`](https://github.com/Josepdal/DBTeamV3/blob/5ff040368c26f776aa64cc130b980863bf67db22/bot/methods.lua#L162)

pin_msg :
[`disable_notification_ > disable_notification`](https://github.com/Josepdal/DBTeamV3/blob/5ff040368c26f776aa64cc130b980863bf67db22/bot/methods.lua#L171)

kick_user :
[`"chatMemberStatusKicked" > "chatMemberStatusBanned"`](https://github.com/Josepdal/DBTeamV3/blob/5ff040368c26f776aa64cc130b980863bf67db22/bot/methods.lua#L188)

promoteToAdmin :
[`"chatMemberStatusModerator" > "chatMemberStatusAdministrator"`](https://github.com/Josepdal/DBTeamV3/blob/5ff040368c26f776aa64cc130b980863bf67db22/bot/methods.lua#L188)

getChannelMembers :
[`"channelMembers" .. filter > "channelMembersFilter" .. filter`](https://github.com/Josepdal/DBTeamV3/blob/5ff040368c26f776aa64cc130b980863bf67db22/bot/methods.lua#L307)

kick_resolve_cb :
[`"chatMemberStatusKicked" > "chatMemberStatusBanned"`](https://github.com/Josepdal/DBTeamV3/blob/5ff040368c26f776aa64cc130b980863bf67db22/bot/methods.lua#L333)

getInputFile :
[`path_ > path`](https://github.com/Josepdal/DBTeamV3/blob/5ff040368c26f776aa64cc130b980863bf67db22/bot/methods.lua#L408)
[`id_ > id`](https://github.com/Josepdal/DBTeamV3/blob/5ff040368c26f776aa64cc130b980863bf67db22/bot/methods.lua#L410)
[`persistent_id_ > persistent_id`](https://github.com/Josepdal/DBTeamV3/blob/5ff040368c26f776aa64cc130b980863bf67db22/bot/methods.lua#L412)

sendSticker :
[`sticker_ > sticker`](https://github.com/Josepdal/DBTeamV3/blob/5ff040368c26f776aa64cc130b980863bf67db22/bot/methods.lua#L420)
[`width_ > width`](https://github.com/Josepdal/DBTeamV3/blob/5ff040368c26f776aa64cc130b980863bf67db22/bot/methods.lua#L421)
[`height_ > height`](https://github.com/Josepdal/DBTeamV3/blob/5ff040368c26f776aa64cc130b980863bf67db22/bot/methods.lua#L422)

sendVideo :
[`added_sticker_file_ids_ > added_sticker_file_ids`](https://github.com/Josepdal/DBTeamV3/blob/5ff040368c26f776aa64cc130b980863bf67db22/bot/methods.lua#L501)

[resolve_cb](https://github.com/Josepdal/DBTeamV3/blob/5ff040368c26f776aa64cc130b980863bf67db22/bot/methods.lua#L231)

**Comment by Josepdal** [comment]
Thank you so much. Next time, you can send us a pull request to be a contributor 👍
